#! /bin/sh
# /etc/init.d/autoshutdown
#

### BEGIN INIT INFO
# Provides:          autoshutdown
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# Some things that run always


# Carry out specific functions when asked to by the system
case "$1" in
start)
	echo "Starting script autoshutdown"
	/usr/local/bin/autoshutdown.sh &
	;;
stop)
	echo "Stopping script autoshutdown"
	;;
*)
	echo "Usage: /etc/init.d/autoshutdown {start|stop}"
	exit 1
	;;
esac

exit 0 
